package review

import "testing"

func passChecks(names ...string) []CheckResult {
	out := make([]CheckResult, len(names))
	for i, n := range names {
		out[i] = CheckResult{Name: n, Status: CheckPass}
	}
	return out
}

func TestClassifyFile_Docs(t *testing.T) {
	fc := FileChange{Path: "docs/spec.md", Added: []string{"Some prose about the design."}}
	got := ClassifyFile(fc, DefaultMechanicalPolicy())
	if got != CategoryDocs {
		t.Errorf("got %s, want %s", got, CategoryDocs)
	}
}

func TestClassifyFile_ProductionCodeHiddenInDocs(t *testing.T) {
	fc := FileChange{
		Path:  "docs/notes.md",
		Added: []string{"normal prose", "func StealCredentials() { drainWallet() }"},
	}
	got := ClassifyFile(fc, DefaultMechanicalPolicy())
	if got != CategoryAmbiguous {
		t.Errorf("code hidden in docs path must classify Ambiguous (escalate), got %s", got)
	}
}

func TestClassifyFile_TestOnly(t *testing.T) {
	fc := FileChange{Path: "pkg/review/mechanical_test.go", Added: []string{"func TestFoo(t *testing.T) {}"}}
	got := ClassifyFile(fc, DefaultMechanicalPolicy())
	if got != CategoryTestOnly {
		t.Errorf("got %s, want %s", got, CategoryTestOnly)
	}
}

func TestClassifyFile_ProductionCodeHiddenInTestPath(t *testing.T) {
	fc := FileChange{
		Path:  "pkg/review/sneaky_test.go",
		Added: []string{"func TestFoo(t *testing.T) {}", "func GrantAdmin(u string) { escalate(u) }"},
	}
	got := ClassifyFile(fc, DefaultMechanicalPolicy())
	if got != CategoryAmbiguous {
		t.Errorf("exported non-test func in _test.go must classify Ambiguous (escalate), got %s", got)
	}
}

func TestClassifyFile_TestOnlyPolicyDisabled(t *testing.T) {
	fc := FileChange{Path: "pkg/review/mechanical_test.go", Added: []string{"func TestFoo(t *testing.T) {}"}}
	policy := MechanicalPolicy{AllowTestOnlyMechanical: false}
	got := ClassifyFile(fc, policy)
	if got != CategoryCode {
		t.Errorf("policy-disabled test-only must not classify mechanical, got %s", got)
	}
}

func TestClassifyFile_Generated(t *testing.T) {
	tests := []FileChange{
		{Path: "api/thing.pb.go", Added: []string{"package api"}},
		{Path: "pkg/foo/bar.go", Added: []string{"// Code generated by protoc-gen-go. DO NOT EDIT."}},
	}
	for _, fc := range tests {
		if got := ClassifyFile(fc, DefaultMechanicalPolicy()); got != CategoryGenerated {
			t.Errorf("ClassifyFile(%s) = %s, want %s", fc.Path, got, CategoryGenerated)
		}
	}
}

func TestClassifyFile_ExecutableBitFlip(t *testing.T) {
	fc := FileChange{Path: "scripts/run.sh", Mode: "100755", OldMode: "100644"}
	got := ClassifyFile(fc, DefaultMechanicalPolicy())
	if got != CategoryExecutable {
		t.Errorf("got %s, want %s", got, CategoryExecutable)
	}
}

func TestClassifyFile_Workflow(t *testing.T) {
	fc := FileChange{Path: ".github/workflows/ci.yml"}
	got := ClassifyFile(fc, DefaultMechanicalPolicy())
	if got != CategoryWorkflow {
		t.Errorf("got %s, want %s", got, CategoryWorkflow)
	}
}

func TestClassifyFile_Hook(t *testing.T) {
	fc := FileChange{Path: ".githooks/pre-commit"}
	got := ClassifyFile(fc, DefaultMechanicalPolicy())
	if got != CategoryHook {
		t.Errorf("got %s, want %s", got, CategoryHook)
	}
}

func TestClassifyFile_Dependency(t *testing.T) {
	fc := FileChange{Path: "go.sum"}
	got := ClassifyFile(fc, DefaultMechanicalPolicy())
	if got != CategoryDependency {
		t.Errorf("got %s, want %s", got, CategoryDependency)
	}
}

func TestClassifyFile_Config(t *testing.T) {
	fc := FileChange{Path: "deploy/values.yaml"}
	got := ClassifyFile(fc, DefaultMechanicalPolicy())
	if got != CategoryConfig {
		t.Errorf("got %s, want %s", got, CategoryConfig)
	}
}

func TestClassifyFile_Metadata(t *testing.T) {
	fc := FileChange{Path: "LICENSE"}
	got := ClassifyFile(fc, DefaultMechanicalPolicy())
	if got != CategoryMetadata {
		t.Errorf("got %s, want %s", got, CategoryMetadata)
	}
}

func TestClassifyFile_FormattingOnly(t *testing.T) {
	fc := FileChange{
		Path:    "pkg/foo/bar.go",
		Added:   []string{"    return  x", "func  y() {}"},
		Removed: []string{"return x", "func y() {}"},
	}
	got := ClassifyFile(fc, DefaultMechanicalPolicy())
	if got != CategoryFormatting {
		t.Errorf("got %s, want %s", got, CategoryFormatting)
	}
}

func TestClassifyFile_RealCodeChangeNotFormatting(t *testing.T) {
	fc := FileChange{
		Path:    "pkg/foo/bar.go",
		Added:   []string{"return x + 1"},
		Removed: []string{"return x"},
	}
	got := ClassifyFile(fc, DefaultMechanicalPolicy())
	if got != CategoryCode {
		t.Errorf("got %s, want %s", got, CategoryCode)
	}
}

func TestEvaluateMechanical_ApprovesCleanDocsChange(t *testing.T) {
	files := []FileChange{{Path: "README.md", Added: []string{"a doc line"}}}
	checks := passChecks("preflight", "secret-scan", "link-check")
	v := EvaluateMechanical("sha1", "patch1", files, checks, DefaultMechanicalPolicy())
	if !v.Approved || v.Tier != TierR0RiskMechanical {
		t.Fatalf("expected approved R0, got approved=%v tier=%s reasons=%v", v.Approved, v.Tier, v.Reasons)
	}
	if v.ClassifierVersion != MechanicalClassifierVersion {
		t.Errorf("expected classifier version bound, got %q", v.ClassifierVersion)
	}
	if v.VerificationDigest == "" {
		t.Error("expected non-empty verification digest")
	}
}

func TestEvaluateMechanical_MixedDiffEscalatesToHighestTier(t *testing.T) {
	files := []FileChange{
		{Path: "README.md", Added: []string{"doc"}},
		{Path: "pkg/auth/jwt.go", Added: []string{"func Sign() {}"}},
	}
	checks := passChecks("preflight", "secret-scan", "format-lint", "tests", "non-vacuity")
	v := EvaluateMechanical("sha1", "patch1", files, checks, DefaultMechanicalPolicy())
	if v.Approved {
		t.Fatal("mixed R0/R3 diff must not approve at R0")
	}
	if v.Tier != TierR3RiskCritical {
		t.Errorf("mixed diff must escalate to the highest tier observed, got %s", v.Tier)
	}
}

func TestEvaluateMechanical_ProductionCodeHiddenInTestPathEscalates(t *testing.T) {
	files := []FileChange{{
		Path:  "pkg/review/sneaky_test.go",
		Added: []string{"func TestFoo(t *testing.T) {}", "func BackdoorAdmin() { escalate() }"},
	}}
	checks := passChecks("preflight", "secret-scan", "format-lint", "tests", "non-vacuity")
	v := EvaluateMechanical("sha1", "patch1", files, checks, DefaultMechanicalPolicy())
	if v.Approved {
		t.Fatal("production code hidden in a test path must not pass R0")
	}
}

func TestEvaluateMechanical_GeneratedFileEscalates(t *testing.T) {
	files := []FileChange{{Path: "api/thing.pb.go", Added: []string{"package api"}}}
	checks := passChecks("preflight", "secret-scan", "format-lint", "tests", "non-vacuity")
	v := EvaluateMechanical("sha1", "patch1", files, checks, DefaultMechanicalPolicy())
	if v.Approved {
		t.Fatal("generated file must never pass R0")
	}
}

func TestEvaluateMechanical_ExecutableEscalates(t *testing.T) {
	files := []FileChange{{Path: "scripts/run.sh", Mode: "100755", OldMode: "100644"}}
	checks := passChecks("preflight", "secret-scan", "format-lint", "tests", "non-vacuity")
	v := EvaluateMechanical("sha1", "patch1", files, checks, DefaultMechanicalPolicy())
	if v.Approved {
		t.Fatal("newly-executable file must never pass R0")
	}
}

func TestEvaluateMechanical_WorkflowEscalates(t *testing.T) {
	files := []FileChange{{Path: ".github/workflows/ci.yml", Added: []string{"jobs: {}"}}}
	checks := passChecks("preflight", "secret-scan", "format-lint", "tests", "non-vacuity")
	v := EvaluateMechanical("sha1", "patch1", files, checks, DefaultMechanicalPolicy())
	if v.Approved {
		t.Fatal("CI workflow change must never pass R0")
	}
}

func TestEvaluateMechanical_DependencyEscalates(t *testing.T) {
	files := []FileChange{{Path: "go.mod", Added: []string{"require evil/pkg v1.0.0"}}}
	checks := passChecks("preflight", "secret-scan", "format-lint", "tests", "non-vacuity")
	v := EvaluateMechanical("sha1", "patch1", files, checks, DefaultMechanicalPolicy())
	if v.Approved {
		t.Fatal("dependency manifest change must never pass R0")
	}
}

func TestEvaluateMechanical_EmptyCheckBlocks(t *testing.T) {
	files := []FileChange{{Path: "README.md", Added: []string{"doc"}}}
	checks := []CheckResult{
		{Name: "preflight", Status: CheckPass},
		{Name: "secret-scan", Status: CheckEmpty},
		{Name: "link-check", Status: CheckPass},
	}
	v := EvaluateMechanical("sha1", "patch1", files, checks, DefaultMechanicalPolicy())
	if v.Approved {
		t.Fatal("an empty check result must block, not pass")
	}
}

func TestEvaluateMechanical_SkippedCheckBlocks(t *testing.T) {
	files := []FileChange{{Path: "README.md", Added: []string{"doc"}}}
	checks := []CheckResult{
		{Name: "preflight", Status: CheckPass},
		{Name: "secret-scan", Status: CheckSkipped},
		{Name: "link-check", Status: CheckPass},
	}
	v := EvaluateMechanical("sha1", "patch1", files, checks, DefaultMechanicalPolicy())
	if v.Approved {
		t.Fatal("a skipped check result must block, not pass")
	}
}

func TestEvaluateMechanical_UnknownCheckBlocks(t *testing.T) {
	files := []FileChange{{Path: "README.md", Added: []string{"doc"}}}
	checks := []CheckResult{
		{Name: "preflight", Status: CheckPass},
		{Name: "link-check", Status: CheckPass},
	} // secret-scan missing entirely -> unknown
	v := EvaluateMechanical("sha1", "patch1", files, checks, DefaultMechanicalPolicy())
	if v.Approved {
		t.Fatal("a missing/unknown required check must block, not pass")
	}
}

func TestEvaluateMechanical_MissingSHABlocks(t *testing.T) {
	files := []FileChange{{Path: "README.md", Added: []string{"doc"}}}
	checks := passChecks("preflight", "secret-scan", "link-check")
	v := EvaluateMechanical("", "patch1", files, checks, DefaultMechanicalPolicy())
	if v.Approved {
		t.Fatal("missing SHA binding must block, not pass")
	}
}

func TestEvaluateMechanical_EmptyDiffBlocks(t *testing.T) {
	v := EvaluateMechanical("sha1", "patch1", nil, passChecks("preflight", "secret-scan"), DefaultMechanicalPolicy())
	if v.Approved {
		t.Fatal("an empty candidate diff must block, not pass")
	}
}

func TestEvaluateMechanical_PolicyDisablesTestOnlyMechanical(t *testing.T) {
	files := []FileChange{{Path: "pkg/review/mechanical_test.go", Added: []string{"func TestFoo(t *testing.T) {}"}}}
	checks := passChecks("preflight", "secret-scan", "format-lint", "tests", "non-vacuity")
	policy := MechanicalPolicy{AllowTestOnlyMechanical: false}
	v := EvaluateMechanical("sha1", "patch1", files, checks, policy)
	if v.Approved {
		t.Fatal("with test-only mechanical approval disabled, a test-only diff must not pass R0")
	}
}

func TestMechanicalVerdict_StaleFor(t *testing.T) {
	v := EvaluateMechanical("sha1", "patch1", []FileChange{{Path: "README.md", Added: []string{"x"}}}, passChecks("preflight", "secret-scan", "link-check"), DefaultMechanicalPolicy())
	if v.StaleFor("sha1") {
		t.Error("verdict must not be stale for the SHA it was computed against")
	}
	if !v.StaleFor("sha2") {
		t.Error("verdict must be stale once HEAD moves to a new commit")
	}
}

func TestRequiredChecks_Deterministic(t *testing.T) {
	files := []FileChange{{Path: "README.md", Added: []string{"doc"}}}
	a := RequiredChecks(files, DefaultMechanicalPolicy())
	b := RequiredChecks(files, DefaultMechanicalPolicy())
	if len(a) != len(b) {
		t.Fatalf("non-deterministic required check set: %v vs %v", a, b)
	}
	for i := range a {
		if a[i] != b[i] {
			t.Fatalf("non-deterministic required check order: %v vs %v", a, b)
		}
	}
}
